// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haljalvfaalbuxkppchg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhbGphbHZmYWFsYnV4a3BwY2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDMwNTcsImV4cCI6MjA3MTI3OTA1N30.FaUP2SVRNYD6CHs5yLZdnjO1WogaVSRQ-UlAQUBoDK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});